services:
  bot:
    depends_on:
      - db
      - chartmaker
      - redis
    build:
      dockerfile: Dockerfile.goapps
      context: .
      args:
        APPNAME: main
    restart: unless-stopped
    env_file: .env
  chartmaker:
    build:
      context: .
      dockerfile: chartmaker/Dockerfile
      target: runner
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  redis:
    image: redis:7-alpine
    volumes:
      - mapleculverttracker_redis_data:/data
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    volumes:
      - mapleculverttracker_pg_data:/var/lib/postgresql/data
      - ./sqlfiles:/root/sqlfiles
    restart: unless-stopped
    env_file:
      - .env
  nginx:
    depends_on:
      - web
      - bot
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  web:
    build:
      context: .
      dockerfile: culvert-web/Dockerfile
      target: runner
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  periodicredis:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.goapps
      context: .
      args:
        APPNAME: periodicredis
    restart: unless-stopped
    env_file: .env
volumes:
  mapleculverttracker_pg_data:
  mapleculverttracker_redis_data:
