services:
  bot:
    depends_on:
      - db16
      - chartmaker
      - dragonfly
    build:
      dockerfile: Dockerfile.goapps
      context: .
      args:
        APPNAME: main
    restart: unless-stopped
    env_file: .env
  chartmaker:
    build:
      context: .
      dockerfile: chartmaker/Dockerfile
      target: runner
    restart: unless-stopped
    init: true
    environment:
      - NODE_ENV=production
  dragonfly:
    image: ghcr.io/dragonflydb/dragonfly:v1.17.1-ubuntu
    ulimits:
      memlock: -1
    volumes:
      - mapleculverttracker_dragonfly_data:/data
  db16:
    image: postgres:16-alpine
    volumes:
      - mapleculverttracker_pg16_data:/var/lib/postgresql/data
      - ./sqlfiles:/root/sqlfiles
    restart: unless-stopped
    env_file:
      - .env
  nginx:
    depends_on:
      - web
      - bot
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  web:
    build:
      context: .
      dockerfile: culvert-web/Dockerfile
      target: runner
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    init: true
  periodicredis:
    depends_on:
      - dragonfly
    build:
      dockerfile: Dockerfile.goapps
      context: .
      args:
        APPNAME: periodicredis
    restart: unless-stopped
    env_file: .env
  culvert_reminder:
    depends_on:
      - db16
    build:
      dockerfile: Dockerfile.goapps
      context: .
      args:
        APPNAME: culvert_score_update_reminder
    restart: unless-stopped
    env_file: .env
volumes:
  mapleculverttracker_pg16_data:
  mapleculverttracker_dragonfly_data:
