services:
  bot:
    depends_on:
      - db16
      - chartmaker
      - valkey
    build:
      dockerfile: Dockerfile.goapps
      target: final
      context: .
      args:
        APPNAME: main
    restart: unless-stopped
    env_file: .env
  chartmaker:
    build:
      context: .
      dockerfile: chartmaker/Dockerfile
      target: runner
    restart: unless-stopped
    init: true
    environment:
      - NODE_ENV=production
  valkey:
    image: valkey/valkey:7.2-alpine
    volumes:
      - mapleculverttracker_valkey_data:/data
    restart: unless-stopped
  db16:
    image: postgres:16-alpine
    volumes:
      - mapleculverttracker_pg16_data:/var/lib/postgresql/data
      - ./sqlfiles:/root/sqlfiles
    restart: unless-stopped
    env_file:
      - .env
  nginx:
    depends_on:
      - web
      - bot
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  web:
    build:
      context: .
      dockerfile: culvert-web/Dockerfile
      target: runner
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    init: true
  periodicredis:
    depends_on:
      - valkey
    build:
      dockerfile: Dockerfile.goapps
      target: final
      context: .
      args:
        APPNAME: periodicredis
    restart: unless-stopped
    env_file: .env
  cron:
    build:
      context: .
      dockerfile: Dockerfile.goapps
      target: cron
      args:
        APPNAME: auto_backup
    restart: unless-stopped
    env_file:
      - .env
    init: true
    entrypoint: sh
    command: ['-c', '/usr/sbin/crond -f -c /etc/cron']
    # TODO: BACKFILL CRON IMAGE AND REMOVE REMINDER IMAGE FROM PROD
volumes:
  mapleculverttracker_pg16_data:
  mapleculverttracker_valkey_data:
