FROM golang:1.20-alpine AS builder
COPY go.mod go.sum /root/src/
RUN cd /root/src && go mod download
COPY cmd /root/src/cmd/
COPY internal /root/src/internal
RUN cd /root/src && go build -o /root/main cmd/main/main.go

FROM alpine:latest
COPY --from=builder /root/main /root/
WORKDIR /root
ENTRYPOINT [ "/root/main" ]