services:
  bot:
    depends_on:
      - db16
      - chartmaker
      - valkey
    image: ghcr.io/slazurin/maple-culvert-tracker/bot:HEAD
    restart: unless-stopped
    env_file: .env
  chartmaker:
    image: ghcr.io/slazurin/maple-culvert-tracker/chartmaker:HEAD
    restart: unless-stopped
    init: true
    environment:
      - NODE_ENV=production
  valkey:
    image: valkey/valkey:7.2-alpine
    volumes:
      - mapleculverttracker_valkey_data:/data
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  db16:
    image: postgres:16-alpine
    volumes:
      - mapleculverttracker_pg16_data:/var/lib/postgresql/data
      - ./sqlfiles:/root/sqlfiles
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  nginx:
    depends_on:
      - web
      - bot
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  web:
    image: ghcr.io/slazurin/maple-culvert-tracker/web:HEAD
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    init: true
  periodicredis:
    depends_on:
      - valkey
    image: ghcr.io/slazurin/maple-culvert-tracker/periodicredis:HEAD
    restart: unless-stopped
    env_file: .env
  cron:
    image: ghcr.io/slazurin/maple-culvert-tracker/cron:HEAD
    restart: unless-stopped
    env_file:
      - .env
    init: true
    entrypoint: sh
    command: ['-c', '/usr/sbin/crond -f -c /etc/cron']
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  mapleculverttracker_pg16_data:
  mapleculverttracker_valkey_data:
