packages:
  - chartmaker
  - culvert-web

minimumReleaseAge: 2880

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  express@>=5.0.0 <5.2.0: '>=5.2.0'
  react-router@>=7.0.0 <7.12.0: '>=7.12.0'
  react-router@>=7.0.0 <=7.11.0: '>=7.12.0'
