packages:
  - chartmaker
  - culvert-web

allowBuilds:
  esbuild: true

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - qs@6.15.2

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
