packages:
  - chartmaker
  - culvert-web

onlyBuiltDependencies:
  - esbuild

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'

minimumReleaseAge: 2880
