# Apply this config to run with no TLS, without traefik
services:
  traefik:
    depends_on:
      - web
      - bot
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports: !override
      - 8080:8080
    command: []
