# Apply this config to run with no TLS, without traefik
services:
  traefik:
    restart: unless-stopped
    image: nginx:stable-alpine-slim
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports: !override
      - 8080:8080
    command: []
