//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DiscordPbAnnounecments = newDiscordPbAnnounecmentsTable("public", "discord_pb_announecments", "")

type discordPbAnnounecmentsTable struct {
	postgres.Table

	// Columns
	Week       postgres.ColumnDate
	MessageID  postgres.ColumnString
	Part       postgres.ColumnInteger
	TotalParts postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DiscordPbAnnounecmentsTable struct {
	discordPbAnnounecmentsTable

	EXCLUDED discordPbAnnounecmentsTable
}

// AS creates new DiscordPbAnnounecmentsTable with assigned alias
func (a DiscordPbAnnounecmentsTable) AS(alias string) *DiscordPbAnnounecmentsTable {
	return newDiscordPbAnnounecmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DiscordPbAnnounecmentsTable with assigned schema name
func (a DiscordPbAnnounecmentsTable) FromSchema(schemaName string) *DiscordPbAnnounecmentsTable {
	return newDiscordPbAnnounecmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DiscordPbAnnounecmentsTable with assigned table prefix
func (a DiscordPbAnnounecmentsTable) WithPrefix(prefix string) *DiscordPbAnnounecmentsTable {
	return newDiscordPbAnnounecmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DiscordPbAnnounecmentsTable with assigned table suffix
func (a DiscordPbAnnounecmentsTable) WithSuffix(suffix string) *DiscordPbAnnounecmentsTable {
	return newDiscordPbAnnounecmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDiscordPbAnnounecmentsTable(schemaName, tableName, alias string) *DiscordPbAnnounecmentsTable {
	return &DiscordPbAnnounecmentsTable{
		discordPbAnnounecmentsTable: newDiscordPbAnnounecmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newDiscordPbAnnounecmentsTableImpl("", "excluded", ""),
	}
}

func newDiscordPbAnnounecmentsTableImpl(schemaName, tableName, alias string) discordPbAnnounecmentsTable {
	var (
		WeekColumn       = postgres.DateColumn("week")
		MessageIDColumn  = postgres.StringColumn("message_id")
		PartColumn       = postgres.IntegerColumn("part")
		TotalPartsColumn = postgres.IntegerColumn("total_parts")
		allColumns       = postgres.ColumnList{WeekColumn, MessageIDColumn, PartColumn, TotalPartsColumn}
		mutableColumns   = postgres.ColumnList{MessageIDColumn, TotalPartsColumn}
		defaultColumns   = postgres.ColumnList{}
	)

	return discordPbAnnounecmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Week:       WeekColumn,
		MessageID:  MessageIDColumn,
		Part:       PartColumn,
		TotalParts: TotalPartsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
